Add HDR calibration to GI settings page
neon-nyan/Collapse pull request #270
Opened 2023-09-21 16:10 UTC by shatyuka

Adds HDR calibration images to the settings page:
![screen shot](https://github.com/neon-nyan/Collapse/assets/31368738/750e71a2-f200-4612-a52b-dc59ee8325ad)

Other adjustments:
- Hide HDR calibration panel by default, for it's much bigger than before.
- Little changes of help tooltips.

2023-09-22 14:34 UTC, bagusnl commented
Can I get a confirmation that what shown in the Collapse calibration page is similar (or similar enough) as the one in-game?
I don't have access to HDR monitor so I couldn't test sorry

2023-09-22 14:51 UTC, MapleHinata commented
> Can I get a confirmation that what shown in the Collapse calibration page is similar (or similar enough) as the one in-game? I don't have access to HDR monitor so I couldn't test sorry

I tested it on my display and it looks very close (if not identical) to what the game shows. 
Nice job, @shatyuka.

2023-09-22 14:54 UTC, bagusnl commented
Thank you for the confirmation @MapleHinata !
My only bit of gripe is that the 1st HDR Calibration image is square so it looks a bit off in my eyes. Can it have a white background to match the width of the other images as well?

For the other code, I've done a short look through and all seems good, will do a thorough look into it soon

2023-09-22 17:11 UTC, shatyuka commented
@bagusnl Is this ok?
<img src="https://github.com/neon-nyan/Collapse/assets/31368738/26c9562d-a77a-4734-95f3-e8a211f2e3a0" width="50%"/>

2023-09-22 17:37 UTC, bagusnl commented
Looks fine on me IMO

2023-09-22 23:48 UTC, bagusnl commented
I checked out your branch and tried to build it. It seems that the 1st panel image is broken somehow and keep only displaying white on me. I tested both on Debug and Publish and same behavior seen. It does spat out some ArgumentException and IOException in the debug output.
```
System.ArgumentException: Value does not fall within the expected range.
   at CollapseLauncher.Pages.GenshinGameSettingsPage.GetAppFileAsync(Uri uri) in F:\GitHub\Collapse\CollapseLauncher\XAMLs\MainApp\Pages\GenshinGameSettingsPage.xaml.cs:line 394
   ```
![image](https://github.com/neon-nyan/Collapse/assets/28079733/0b17a416-89f9-4db5-8bc7-864ceac981da)

2023-09-23 04:43 UTC, shatyuka commented
Actually the first image is just a white icon displayed on a white background, and the slider controls the brightness of the icon. So it appears completely white on SDR monitor.
For the ArgumentException, I have a try-catch block to handle it. It may be because your debug mode takes over exception handling.
`ms-appx://` uri failed to be opened in c# code, but works in xaml for an unpackaged app. Maybe there is a better way to detect whether this application is packaged? IDK

2023-09-23 14:17 UTC, bagusnl commented
Gotchu, thanks for the clarification!

2023-09-24 03:07 UTC, Cryotechnic requested changes
Just a small change overall, the rest looks great. Thanks for your contribution!

2023-09-24 03:07 UTC, Cryotechnic commented on CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml.cs
> +using Windows.Storage;
Really minor, but ideally, we'd like to group the imports together, such that imports are grouped by packages.

2023-09-24 03:07 UTC, Cryotechnic commented
Again, this is on SDR and is just a minor visual bug, but the second image does not fully render. I don't think it really matters since SDR display users will never enable this option, but just something to take note of.

Image in question:
![image](https://github.com/neon-nyan/Collapse/assets/9833218/4576ff86-10db-4cbf-887c-72f19be54563)

The rest looks good!

2023-09-24 04:55 UTC, bagusnl reviewed
Good work overall on the implementation!
Some things to discuss are:
1. Do we need to have tooltip if its already explained in the FlyOut?
2. Is there a way to tell user that they did not have HDR capable monitor?
The API to check if the HDR monitor is available can be done through [Windows.Graphics.Display.IsAdvancedColorKindAvailable](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.display.advancedcolorinfo.isadvancedcolorkindavailable?view=winrt-22621)
This is to eliminate user confusion when the settings keeps being reverted and the image shown is blank

2023-09-24 04:55 UTC, bagusnl commented on CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml
> +                                                        <ToolTip Content="{x:Bind helper:Locale.Lang._GenshinGameSettingsPage.Graphics_HDR_MaxLuminosity_Help}"/>
Same as above

2023-09-24 04:55 UTC, bagusnl commented on CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml
> +                                                        <ToolTip Content="{x:Bind helper:Locale.Lang._GenshinGameSettingsPage.Graphics_HDR_SceneBrightness_Help}"/>
Same as above

2023-09-25 14:56 UTC, shatyuka commented
I have tried Windows.Graphics.Display.DisplayInformation, but it's only available in UWP app.
I did further research and it turns out I need to use **Microsoft**.Graphics.Display.DisplayInformation :(

2023-09-25 15:04 UTC, bagusnl commented
I am so sorry I sent the wrong documentation :(

2023-09-25 15:29 UTC, bagusnl approved these changes
Good work on the overall implementation!
I have tested on Release build and everything seems good, the code looks good as well. 

Sorry for asking so much to you. Thank you so much for your contribution for Collapse project! <3

2023-09-26 12:32 UTC, Cryotechnic commented
LGTM!

Thanks for your contributions! Going to merge now.

2023-09-26 12:33 UTC, merged